openapi: "3.0.0"
info:
  title: KRI Eight - API
  version: "1.5.2"
  description: KRI Eight - API
components:
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: authorization
      in: header
definitions:
  address:
    type: object
    properties:
      id:
        type: integer
        example: 1
        description: Internal address ID
      street:
        type: string
        example: 1234 Main Street
        description: Street address
      city:
        type: string
        example: San Francisco
        description: City
      state:
        type: string
        example: CA
        description: State
      zip:
        type: string
        example: 94111
        description: Zip code
  createdAt:
    type: string
    example: 2023-01-28T03:37:33.114Z
    description: Creation date
  credentials:
    type: object
    properties:
      username:
        type: string
        example: Rodrigo Sebastián
        description: User name
      email:
        type: string
        example: rodrigo@krieight.com
        description: User email
      password:
        type: string
        example: 123456
        description: User password
  customer:
    type: object
    properties:
      id:
        type: UUID
        example: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        description: Internal customer ID
      person:
        $ref: "#/definitions/person"
  customers:
    type: array
    items:
      $ref: "#/definitions/customer"
  error:
    type: object
    properties:
      message:
        type: string
        example: Error message
        description: Error message
  signIn:
    type: object
    properties:
      message:
        type: string
        example: User was logged in successfully
        description: User was logged in successfully
      data:
        $ref: "#/definitions/user"
  signUp:
    type: object
    properties:
      message:
        type: string
        example: User was registered successfully
        description: User was registered successfully
      data:
        type: object
        properties:
          user:
            $ref: "#/definitions/user"
  updatedAt:
    type: string
    example: 2023-01-28T03:37:33.114Z
    description: Last update date
  person:
    type: object
    properties:
      id:
        type: integer
        example: 1
        description: Internal person ID
      name:
        type: string
        example: Kri Eight
        description: Person name
      number:
        type: string
        example: 7441234567
        description: Person cellphone number
      address:
        $ref: "#/definitions/address"
  role:
    type: object
    properties:
      id:
        type: integer
        example: 1
        description: Internal role ID
      name:
        type: string
        example: admin
        description: Role name
  user:
    type: object
    properties:
      id:
        type: uuid
        example: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        description: Internal user ID
      username:
        type: string
        example: Admin KRI
        description: User name
      email:
        type: string
        example: admin@krieight.com
        description: User email
      active:
        type: boolean
        example: true
        description: User active status
      role:
        $ref: "#/definitions/role"
      person:
        $ref: "#/definitions/person"
  product:
    type: object
    properties:
      sku:
        type: string
        example: 123456
        description: Product SKU
      name:
        type: string
        example: Product 1
        description: Product name
      description:
        type: string
        example: Product 1 description
        description: Product description
      price:
        type: number
        format: currency
        example: 100
        description: Product price
      kg_price:
        type: number
        format: currency
        example: 100
        description: Product price per kg
      image:
        type: string
        format: binary
        description: Product image
      weight:
        type: number
        example: 100
        description: Product weight
      active:
        type: boolean
        example: true
        description: Product active status
  sale_details:
    type: array
    properties:
      product:
        $ref: "#/definitions/product"
      quantity:
        type: integer
        example: 1
        description: Product quantity
      price:
        type: number
        format: currency
        example: 100
        description: Product price
  store:
    type: object
    properties:
      id:
        type: integer
        example: 1
        description: Internal store ID
      name:
        type: string
        example: Store 1
        description: Store name
      address:
        $ref: "#/definitions/address"
      user:
        $ref: "#/definitions/user"
  sale:
    type: object
    properties:
      id:
        type: integer
        example: 1
        description: Internal sale ID
      store:
        $ref: "#/definitions/store"
      customer:
        $ref: "#/definitions/customer"
      date:
        type: string
        example: 2023-01-28T03:37:33.114Z
        description: Sale date
      total:
        type: number
        format: currency
        example: 100
        description: Sale total
      details:
        $ref: "#/definitions/sale_details"
  serialized_user:
    type: object
    properties:
      type:
        type: string
        example: user
        description: Data type
      id:
        type: uuid
        example: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        description: Internal user ID
      attributes:
        type: object
        properties:
          username:
            type: string
            example: Admin KRI
            description: User name
          email:
            type: string
            example: admin@krieight.com
            description: User email
          active:
            type: boolean
            example: true
            description: User active status
          role:
            type: string,
            example: Admin
            description: User role
          person:
            $ref: "#/definitions/person"
  serialized_product:
    type: object
    properties:
      type:
        type: string
        example: Product
        description: Data type
      id:
        type: string
        example: 123456
        description: Product SKU
      attributes:
        type: object
        properties:
          name:
            type: string
            example: Product 1
            description: Product name
          description:
            type: string
            example: Product 1 description
            description: Product description
          price:
            type: number
            format: currency
            example: 100
            description: Product price
          kg_price:
            type: number
            format: currency
            example: 100
            description: Product price per kg
          image:
            type: string
            format: binary
            description: Product image
          weight:
            type: number
            example: 100
            description: Product weight
          active:
            type: boolean
            example: true
            description: Product active status
  serialized_customer:
    type: object
    properties:
      type:
        type: string
        example: Customer
        description: Data type
      id:
        type: uuid
        example: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        description: Internal customer ID
      attributes:
        type: object
        properties:
          person:
            $ref: "#/definitions/person"
  token:
    type: string
    example: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    description: JWT token
