paths:
  /api/products:
    get:
      tags:
        - Product
      description: Get all products
      security:
        - Bearer: []
      parameters:
        - name: showDeactivated
          in: query
          description: Show deactivated products
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
  /api/product/:sku:
    get:
      tags:
        - Product
      description: Get a specific product by SKU
      security:
        - Bearer: []
      parameters:
        - name: sku
          in: path
          description: Product SKU
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
    put:
      tags:
        - Product
      description: Update a product
      security:
        - Bearer: []
      parameters:
        - name: sku
          in: path
          description: Product SKU
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/product'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product updated successfully
                  product:
                    $ref: '#/definitions/product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
    delete:
      tags:
        - Product
      description: Deactivate a product
      security:
        - Bearer: []
      parameters:
        - name: sku
          in: path
          description: Product SKU
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product deactivated successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
  /api/product/:
    post:
      tags:
        - Product
      description: Create a new product
      security:
        - Bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/product'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product created successfully
                  product:
                    $ref: '#/definitions/product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/definitions/error'
